---
title: Adam Sisco - About
output: html_document
---

<link rel="stylesheet" href="icon_libraries/fontawesome-free-5.9.0-web/css/all.css"/>

<style>
  .title {
    display: none;
  }
  
  h1 {
    border-bottom-width: 1px;
    border-bottom-style: solid;
    border-bottom-color: black;
  }
  
  .banner-image {
    background-image: linear-gradient(rgba(0, 0, 0, 0.20), rgba(0, 0, 0, 0.20)), url("images/cropped/cropped_ohiorv_tm5_2011123_lrg.jpg");
  }
</style>

# About

---
title: "About"
output: html_document
---

I am currently a graduate student in the [Department of Atmospheric and Environmental Sciences](https://www.albany.edu/atmos/){target="blank"} at the University at Albany, SUNY. I received my B.S. in Geosciences from Mississippi State University in 2016. After completing my undergraduate degree, I spent a semester interning at Oak Ridge National Laboratory and then worked full-time for 2.5 years as a research associate for [NASA IMPACT](https://earthdata.nasa.gov/esds/impact){target="blank"} in Huntsville, AL. Having lived in the Deep South my entire life, I'm now getting a taste of Upstate New York and its remarkably different climate.

I can trace my interest in atmospheric science to September 2004 when Hurricane Ivan struck the Alabama Gulf Coast near Gulf Shores where my family often vacationed in the summer. The historic 2005 Atlantic hurricane season followed, a season so ingrained in me that I still have all 27 storm names memorized. My current research interests, however, were sparked by my firsthand experience of two extreme precipitation events--heavy rainfall and flooding in Tennessee on 1-2 May 2010 and in North Alabama on Christmas morning 2015. Hydrometeorological extreme events like these have left me curious about their upstream origins and the synoptic and mesoscale processes involved in their formation and maintenance. I'm also interested in evaluating the predictability of these events and the environments in which they occur.

My research interests therefore include:

* Midlatitude synoptic-dynamic meteorology
* Extratropical cyclones and their impact on downstream predictability
* Large-scale moisture transport
* Extreme precipitation events
* Probabilistic forecasting

Despite Python reigning supreme in the Earth and atmospheric sciences, I'm a huge <i class="fab fa-r-project"></i> enthusiast. Most of this site, in fact, is written in [R Markdown](https://rmarkdown.rstudio.com/){target="blank"}. In addition to my atmospheric science interests, I'm passionate about data visualization and computational reproducibility in science. I'm also a news junkie, and in my free time, I enjoy reading, laying by the pool, reading while laying by the pool, yoga, listening to my podcast backlog, and cooking new recipes.