---
title: "About this Blog"
author: "[*Adam Sisco*](https://awsisco.github.io)"
date: "June 26, 2019"
output:
  html_document:
    css: css/site_css.css
---

> Few things in this world strike fear into me like the word *blog*.

I therefore hesitated to even include a blog section on my website. I'm a meticulous writer so crafting my words exactly how I want can be quite a time consuming process, not to mention all the questions I would still be asking myself after the fact. Is it too short? Too long? Should I try to funny? Is anyone even interested in what I have to say?

To remedy this, I have adopted the [philosophy of Sean Kross](http://seankross.com/2017/11/06/Enabling-Frequent-Brain-Dumps.html){target="_blank"} in that I'm treating this blog as a collection of notes where I drop figures, code snippets, thoughts, websites, and articles that are maybe a product of some idea I had or inspiration for a new one. Anything that deserves to live somewhere other than my desktop or in a forgotten bookmarks folder is a candidate for this blog-that-is-not-a-blog, at least in the traditional sense.

I intend for these mini brain dumps, if you will, to offer a peak at what I'm up to or what I'm thinking about. More importantly, I hope they are of use to someone else. After all, much of what I've learned outside the classroom can be attributed to thousands of online strangers simply taking the time to share their own tips, explainers, and insightful musings. Happy reading!