---
title: Adam Sisco - CV
output:
  html_document:
    toc: true
    toc_float: true
    css: css/site_css.css
---

<style>
  .title {
    display: none;
  }
  
  .level2 {
    margin-bottom: 20px;
  }
  
  @media(min-width:768px){
    .cv-header {
      display: flex;
    }
    
    .cv-right {
      text-align: right;
    }
  }
  
  .cv-header {
    border-bottom-width: 3px;
    border-bottom-style: solid;
    border-bottom-color: black;
    margin-bottom: 10px;
  }
  
  .cv-header div {
    /*border: 1px #ccc solid;*/
    flex: 1;
  }
</style>
<br/>
<div class="cv-header">
  <div class="cv-left">
  <p style="font-size:36px">Adam W. Sisco</p>
  *Curriculum Vitae*
  <br/>
  
  </div>
  <div class="cv-right">
  Department of Atmospheric and Environmental Sciences  
  University at Albany, State University of New York  
  1400 Washington Ave., Albany, NY 12222  
  Website: https://awsisco.github.io  
  Email: [asisco@albany.edu](mailto:asisco@albany.edu)
  <br/>
  
  </div>
</div>

## Interests
Midlatitude synoptic-dynamic meteorology, extratropical cyclones and their impact on downstream predictability, large-scale moisture transport, extreme precipitation events, probabilistic forecasting, data visualization, computational reproducibility in science

## Education

__M.S. in Atmospheric Science__ [Expected 2021]{style="float:right"}  
University at Albany, State University of New York; Albany, NY

__B.S. in Geosciences; Concentration in Professional Meteorology (*summa cum laude*)__ [2016]{style="float:right"}  
Mississippi State University; Mississippi State, MS

#### Non-degree graduate coursework
__ATS 782: Professional Development__ [Fall 2018]{style="float:right"}  
Proposal writing, time management, research ethics, budget preparation  
University of Alabama in Huntsville

__ESS 509: Applications of Computers in Meteorology__ [Fall 2017]{style="float:right"}   
Tenets of scientific programming, data types, array manipulation, program design  
University of Alabama in Huntsville

## Professional Experience
__University at Albany, State University of New York__; Albany, NY [2019--present]{style="float:right"}  
Graduate Research Assistant, Department of Atmospheric and Environmental Sciences  
Advisor: Ryan D. Torn

__University of Alabama in Huntsville__; Huntsville, AL [2017--2019]{style="float:right"}  
Research Associate, [NASA IMPACT](https://earthdata.nasa.gov/esds/impact){target="_blank"}

* Led the Data Curation for Discovery (DCD) project, tasked with improving discovery and interagency use of NASA Earth observation data
* Organized and conducted meetings with interagency partners and NASA HQ
* Performed science metadata quality reviews and formulated best practices for describing Earth Observing System data
* Prepared and presented oral/poster presentations at meetings and conferences 

__Oak Ridge National Laboratory__; Oak Ridge, TN [Fall 2016]{style="float:right"}  
Intern, Science Undergraduate Laboratory Internship  
Mentor: Olufemi A. Omitaomu

* Assessed the risk sea level rise poses to coastal populations and infrastructure systems
* Prepared and presented oral/poster presentations on research results at on-site symposia 

## Technical Skills
__Programming:__ R, NCL, Python, Unix shell scripting  
__Document preparation:__ LaTeX, R Markdown  
__GIS:__ ArcGIS, QGIS  
__Platforms:__  Linux, Mac, Windows

## Professional Activities
#### Memberships
* American Geophysical Union
* American Meteorological Society

#### Activities
* AMS [Early Career Leadership Academy](https://www.ametsoc.org/index.cfm/ams/education-careers/early-career-leadership-academy/){target="_blank"} [Class of 2019]{style="float:right"}

## Honors and Awards
__NASA Science and Technology Office Peer Award__ [2018]{style="float:right"}  
For cultivating and maintaining a strong relationship with the Department of the Interior and other federal agencies in support of the Data Curation for Discovery project.  
NASA Science and Technology Office 
 
__Best Abstract__ [2016]{style="float:right"}  
Oak Ridge Institute for Science and Education Fall 2016 Poster Session  
Oak Ridge National Laboratory 
 
__Best Poster__ [2016]{style="float:right"}  
Oak Ridge Institute for Science and Education Fall 2016 Poster Session  
Oak Ridge National Laboratory 
 
__Best Cumulative Forecast Score, Team Standings__ [2016]{style="float:right"}  
Spring 2016 WxChallenge Forecasting Competition  
Mississippi State University 
 
__President’s List (GPA ≥ 3.8)__ [2012--2016]{style="float:right"}  
Mississippi State University

## Articles in Preparation
Bugbee, K., J. le Roux, __A. W. Sisco__, P. Staton, I. Garcia-Solera, B. Freitag, B. E. Hernández, R. Ramachandran, and V. Dixon, 2020: Development and use of a metadata quality framework for the Earth sciences. *Earth Sci. Inform.* In preparation.

## Invited Presentations
le Roux, J., K. Bugbee, V. Dixon, __A.W. Sisco__, P. Staton, I. Garcia-Solera, and R. Ramachandran, 2018: A metadata curation approach to improve the discoverability and accessibility of NASA Earth science data. *Developing Innovative Tools and Services to Enable Data Use across Broad User Communities*, Washington, D.C., Amer. Geo. Union, [IN51A-03](https://agu.confex.com/agu/fm18/meetingapp.cgi/Paper/352181){target="_blank"}. 
 
__Sisco, A. W.__, S. Ramdeen, J. Davidson, L. Duffy, and K. Bugbee, 2018: Extending the Climate Data Initiative data collection to GeoPlatform.gov. *Collaboration and Sharing Through GeoPlatform Communities*, Reston, VA, Joint HIFLD/GeoPlatform Session 2018. 
 
__Sisco, A. W.__, K. Bugbee, J. le Roux, P. Staton, B. Freitag, and V. Dixon, 2018: Collaborative metadata curation in support of NASA Earth science data stewardship. *2018 Earth Science Data System Working Group Meeting*, Annapolis, MD.

## Oral Presentations
le Roux, J., K. Bugbee, __A. W. Sisco__, R. Ramachandran, P. Staton, I. Garcia-Solera, C. Woods, A. Kaulfus, J. Miller, B. Freitag, and P. Cheng, 2019: Eliminating science friction: A metadata quality framework for the Earth sciences. *Establishing Trustworthiness and Suitability of Data Products and Services with Content-Rich, Interoperable and Findable Quality Descriptive Information*, Vienna, Austria, European Geosciences Union, [EGU2019-10985](https://meetingorganizer.copernicus.org/EGU2019/EGU2019-10985.pdf){target="_blank"}. 
 
Bugbee, K., __A. W. Sisco__, and J. le Roux, 2019: The alchemy of centralized repositories. *Establishing Trust in Centralized Repositories*, North Bethesda, MD, 2019 Earth Science Information Partners Winter Meeting. 
 
__Sisco, A. W.__, S. Ramdeen, K. Bugbee, J. Davidson, L. Duffy, P. Neal, T. O. Dabolt, A. Whitehurst, and R. Ramachandran, 2018: Extending the Climate Data Initiative to GeoPlatform.gov. *Towards Networks of Trusted Data Repositories in the Earth and Space Sciences*, Washington, D.C., Amer. Geo. Union, [IN24B-07](https://agu.confex.com/agu/fm18/meetingapp.cgi/Paper/416846){target="_blank"}. 
 
Bugbee, K., V. Dixon, R. Ramachandran, D. Shum, J. le Roux, __A. W. Sisco__, P. Staton, and B. E. Hernández, 2018: NASA’s collaborative metadata curation activity to improve Earth science data discovery. *Metadata, Data Models, Semantics, and Collaboration*, Vienna, Austria, European Geosciences Union, [EGU2018-11152](https://meetingorganizer.copernicus.org/EGU2018/EGU2018-11152.pdf){target="_blank"}. 
 
__Sisco, A. W.__, K. Bugbee, D. Shum, K. Baynes, V. Dixon, and R. Ramachandran, 2017: Improving access to NASA Earth science data through collaborative metadata curation. *Approaches for Curation to Data Discovery in the Era of Big Data Variety*, New Orleans, LA, Amer. Geo. Union, [IN13D-05](https://agu.confex.com/agu/fm17/meetingapp.cgi/Paper/218561){target="_blank"}. 
 
__Sisco, A. W.__, and O. A. Omitaomu, 2016: A climate adaptation framework for resilient coastal communities. *Fall 2016 Oak Ridge Institute for Science and Education Research Symposium*, Oak Ridge, TN, Oak Ridge National Laboratory. 

## Poster Presentations
__Sisco, A. W.__, S. Ramdeen, K. Cook, K. Bugbee, J. Davidson, L. Duffy, P. Neal, T. O. Dabolt, A. Whitehurst, and R. Ramachandran, 2019: Improving accessibility of federal Earth science data and services through GeoPlatform.gov. *NASA MSFC Science, Technology, and Engineering Jamboree*, Huntsville, AL, NASA Marshall Space Flight Center. 
 
le Roux, J., K. Bugbee, V. Dixon, __A.W. Sisco__, P. Staton, I. Garcia-Solera, and R. Ramachandran, 2019: A metadata curation approach to improve the discoverability and accessibility of NASA Earth science data. *NASA MSFC Science, Technology, and Engineering Jamboree*, Huntsville, AL, NASA Marshall Space Flight Center. 
 
Hernández, B.E., K. Bugbee, J. le Roux, T. Beaty, M. Hansen, P. Staton, and __A.W. Sisco__, 2017: From the inside-out: Retrospectives on a metadata improvement process to advance the discoverability of NASA’s earth science data. *Approaches for Curation to Data Discovery in the Era of Big Data Variety*, New Orleans, LA, Amer. Geo. Union, [IN21B-0815](https://agu.confex.com/agu/fm17/meetingapp.cgi/Paper/264290){target="_blank"}. 
 
__Sisco, A. W.__, and O. A. Omitaomu, 2016: Developing an analytical risk assessment model for resilient coastal communities. *Science Education Programs at ORNL Fall 2016 Poster Session*, Oak Ridge, TN, Oak Ridge National Laboratory. 

## Field Work
__VORTEX Southeast__ [Spring 2016]{style="float:right"}  

* Launched mobile soundings into severe convective environments 

## Press
ORNL Recent College Graduate Research Profile: [Student’s research prepares coastal cities for natural disasters](https://orise.orau.gov/ornl/experiences/archive/sisco.html){target="_blank"}